version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: mongo-btech
    ports:
      - 27017:27017
    volumes:
      - $HOME/data/mongo-data:/data/btechdb
    restart: always
    networks:
      - local
networks:
  local:
    driver: bridge
